// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOk3bnobPbc-FwQ4Jen1uSS61HEQQqTk',
    appId: '1:200189946663:web:6f314dc5d5341bd0925702',
    messagingSenderId: '200189946663',
    projectId: 'pilot-project-a9f18',
    authDomain: 'pilot-project-a9f18.firebaseapp.com',
    storageBucket: 'pilot-project-a9f18.appspot.com',
    measurementId: 'G-SFYCH35ELL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbR6cPOzUWyff59kw6p5SaWnX4FKb6m64',
    appId: '1:200189946663:android:6cfc390bd4ca0bdb925702',
    messagingSenderId: '200189946663',
    projectId: 'pilot-project-a9f18',
    storageBucket: 'pilot-project-a9f18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNSEPK6iLdXpXdaeFXMgHIeXIFtU15iBw',
    appId: '1:200189946663:ios:fdd4bfc16889fb37925702',
    messagingSenderId: '200189946663',
    projectId: 'pilot-project-a9f18',
    storageBucket: 'pilot-project-a9f18.appspot.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNSEPK6iLdXpXdaeFXMgHIeXIFtU15iBw',
    appId: '1:200189946663:ios:fdd4bfc16889fb37925702',
    messagingSenderId: '200189946663',
    projectId: 'pilot-project-a9f18',
    storageBucket: 'pilot-project-a9f18.appspot.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbOk3bnobPbc-FwQ4Jen1uSS61HEQQqTk',
    appId: '1:200189946663:web:9e06ca5a89b5e058925702',
    messagingSenderId: '200189946663',
    projectId: 'pilot-project-a9f18',
    authDomain: 'pilot-project-a9f18.firebaseapp.com',
    storageBucket: 'pilot-project-a9f18.appspot.com',
    measurementId: 'G-DV37GH13HW',
  );
}
